language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7
  - hhvm

before_install:
  - composer self-update

install:
  - composer require --dev satooshi/php-coveralls
  - composer install --no-interaction --prefer-source

script:
  - mkdir -p logs
  - php vendor/bin/phpunit --coverage-clover logs/clover.xml

after_script:
  - php vendor/bin/coveralls -v
