language: php
sudo: false
php:
  - 5.5
  - 5.6
  - 7
  - hhvm

before_install:
  - composer self-update

install:
  - mkdir -p build/logs
  - composer require --dev satooshi/php-coveralls
  - composer install --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml

after_script:
  - travis_retry vendor/bin/coveralls -v
